TEACHER_AUTHORITIES = [
	'VIEW_MATERIAL',
	'VIEW_MAP',
	'VIEW_CLASSES',
	'VIEW_TASK',
	'ADD_MATERIAL',
	'ADD_CLASS',
	'ADD_STUDENT',
	'ADD_TASK',
	'ADD_CHALLENGE',
	'ADD_ABSENT',
	'VIEW_ABSENT',
	'VIEW_PROFILE',
	'EDIT_PROFILE'
]

STUDENT_AUTHORITIES = [
	'VIEW_MATERIAL',
	'VIEW_MAP',
	'VIEW_CLASSES',
	'VIEW_TASK',
	'VIEW_ABSENT',
	'VIEW_STUDENT_PROFILE'
]

OTHER_AUTHORITIES = [
	'VIEW_MATERIAL',
	'VIEW_MAP',
	'VIEW_CHALLENGE'
	'EDIT_SCHOOL',
	'EDIT_PROFILE',
	'DO_CHALLENGE',
	'ADD_SCHOOL'
]
