TEACHER_AUTHORITIES = [
	'VIEW_PROFILE',
	'JUDGE_TASK',
	'SHARE_TASK',
	'VIEW_ABSENT',
	'SUBMIT_LESSON',
	'VIEW_LESSON',
	'VIEW_ACTIVITY',
	'EDIT_PROFILE',
	'GIVE_TASK',
	'VIEW_TASK',
	'ADD_ABSENT'
]

STUDENT_AUTHORITIES = [
	'VIEW_PROFILE',
	'VIEW_LESSON',
	'VIEW_ACTIVITY',
	'VIEW_TASK_FRAGMENT',
	'DOING_TASK',
	'VIEW_ABSENT',
	'EDIT_PROFILE',
]

OTHER_AUTHORITIES = [
	'VIEW_LESSON',
	'VIEW_MAP',
	'VIEW_CHALLENGE'
	'EDIT_SCHOOL',
	'EDIT_PROFILE',
	'DO_CHALLENGE',
	'ADD_SCHOOL'
]
