"""empty message

Revision ID: a761eb962ccb
Revises: 
Create Date: 2018-08-13 21:14:52.112607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a761eb962ccb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tm_task_score',
    sa.Column('task_score_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tm_task.task_id'], ),
    sa.PrimaryKeyConstraint('task_score_id')
    )
    op.create_table('tm_question_score',
    sa.Column('question_score_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('task_score_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['tm_task_question.question_id'], ),
    sa.ForeignKeyConstraint(['task_score_id'], ['tm_task_score.task_score_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tm_user.user_id'], ),
    sa.PrimaryKeyConstraint('question_score_id')
    )
    op.drop_table('question_score')
    op.drop_table('task_score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_score',
    sa.Column('task_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('total_score', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tm_task.task_id'], name='task_score_task_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['tm_user.user_id'], name='task_score_user_id_fkey'),
    sa.PrimaryKeyConstraint('task_id', 'user_id', name='task_score_pkey')
    )
    op.create_table('question_score',
    sa.Column('question_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('score', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['tm_task_question.question_id'], name='question_score_question_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['tm_user.user_id'], name='question_score_user_id_fkey'),
    sa.PrimaryKeyConstraint('question_id', 'user_id', name='question_score_pkey')
    )
    op.drop_table('tm_question_score')
    op.drop_table('tm_task_score')
    # ### end Alembic commands ###
