"""empty message

Revision ID: b41628e17d04
Revises: ca262656deef
Create Date: 2018-08-14 22:37:10.971697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41628e17d04'
down_revision = 'ca262656deef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tm_task_score', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'tm_task_score', 'tm_user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tm_task_score', type_='foreignkey')
    op.drop_column('tm_task_score', 'user_id')
    # ### end Alembic commands ###
