"""empty message

Revision ID: ca262656deef
Revises: a761eb962ccb
Create Date: 2018-08-13 23:05:24.998456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca262656deef'
down_revision = 'a761eb962ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tm_question_score_task_score_id_fkey', 'tm_question_score', type_='foreignkey')
    op.drop_column('tm_question_score', 'task_score_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tm_question_score', sa.Column('task_score_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('tm_question_score_task_score_id_fkey', 'tm_question_score', 'tm_task_score', ['task_score_id'], ['task_score_id'])
    # ### end Alembic commands ###
