"""empty message

Revision ID: dbde333ae279
Revises: b41628e17d04
Create Date: 2018-08-14 23:20:43.772077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbde333ae279'
down_revision = 'b41628e17d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_question_score_question_id_user_id', 'tm_question_score', ['user_id', 'question_id'])
    op.create_unique_constraint('uix_task_score_task_id_user_id', 'tm_task_score', ['user_id', 'task_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_task_score_task_id_user_id', 'tm_task_score', type_='unique')
    op.drop_constraint('uix_question_score_question_id_user_id', 'tm_question_score', type_='unique')
    # ### end Alembic commands ###
